In [1]:
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('data\n', arr)

넘파이 배열 파일 입출력

In [20]:
np.random.seed(100)
a = np.random.randint(1, 10, (2, 3))
pprint(a)
b = np.random.randint(1, 10, (2, 3))
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
data
 [[9 9 4]
 [8 8 1]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
data
 [[5 3 6]
 [3 3 3]]


In [23]:
# 배열 객체 저장 - 바이너리(2진) 파일
# save(), savez() 함수를 이용해서 배열 객체를 바이너리 형태의 파일로 저장할 수 있다.
# save('파일이름', 배열이름): 배열 1개를 저장한다. 확장명 => npy
# savez('파일이름', 배열이름1, 배열이름2, ...): 배열 여러개를 저장한다. 확장명 => npz

# a 배열을 파일로 저장한다.
np.save('./output/my_array1', a)
# a, b 배열을 파일로 저장한다.
np.savez('./output/my_array2', a, b)

In [29]:
# load() 함수로 npy, npz 파일로부터 배열 데이터를 읽어올 수 있다. 이 때, 확장명을 반드시 적어야 한다.
# npy 파일 읽기
print(np.load('./output/my_array1.npy'))
# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
print(np.load('./output/my_array2.npz')['arr_0'])
print(np.load('./output/my_array2.npz')['arr_1'])

[[9 9 4]
 [8 8 1]]
[[9 9 4]
 [8 8 1]]
[[5 3 6]
 [3 3 3]]


In [37]:
data = np.random.random((3, 4))
pprint(data)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: float64
data
 [[0.1107879  0.3126403  0.45697913 0.65894007]
 [0.25425752 0.64110126 0.20012361 0.65762481]
 [0.77828922 0.7795984  0.61032815 0.30900035]]


In [38]:
# 배열 객체 저장 - 텍스트 파일
# savetxt() 함수로 배열 객체를 텍스트 파일로 저장할 수 있다. => csv 파일, tsv 파일
# savetxt('파일 이름', 데이터, delimiter='구분자')

In [42]:
# data 배열을 텍스트 파일로 저장한다.
# np.savetxt('./output/saved.csv', data) # 구분자를 생략하면 기본값으로 csv 파일로 저장한다.
np.savetxt('./output/saved.csv', data, delimiter=',')
np.savetxt('./output/saved.tsv', data, delimiter='\t')

In [44]:
# loadtxt() 함수로 csv, tsv 파일로부터 배열 데이터를 읽어올 수 있다. 확장명을 반드시 적어야 한다.
print(np.loadtxt('./output/saved.csv', delimiter=','))
print(np.loadtxt('./output/saved.tsv', delimiter='\t'))

[[0.1107879  0.3126403  0.45697913 0.65894007]
 [0.25425752 0.64110126 0.20012361 0.65762481]
 [0.77828922 0.7795984  0.61032815 0.30900035]]
[[0.1107879  0.3126403  0.45697913 0.65894007]
 [0.25425752 0.64110126 0.20012361 0.65762481]
 [0.77828922 0.7795984  0.61032815 0.30900035]]


배열(행렬) 연산 - 산술연산

In [66]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
print(a.shape)
b = np.arange(9, 0, -1).reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [67]:
# 덧셈: +, add()
print(a + b)
print(np.add(a, b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [57]:
# 뺄셈: -, subtract()
print(a - b)
print(np.subtract(a, b))

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [59]:
# 곱셈: *, multiply()
print(a * b)
print(np.multiply(a, b))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [62]:
# 나눗셈: /, divide()
print(a / b)
print(np.divide(a, b))

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [68]:
# 지수
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [69]:
# 제곱근
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [71]:
# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [72]:
# 로그
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [73]:
# 행렬의 내적 => 행렬의 곱
print(np.dot(a, b))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


<img src="./matrix.png" width=1000 align="left"/>

비교 연산

In [74]:
# 배열 요소별 비교: >, <=, <, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [75]:
# 배열 전체 비교: array_equal() 함수를 사용하면 배열 전체를 비교할 수 있다.
print(np.array_equal(a, b))

False


집계 함수

In [ ]:
# 넘파이의 거의 모든 집계 함수는 axis를 기준으로 계산된다. 
# 집계 함수에 axis를 지정하지 않으면 axis=None이 기본값으로 사용된다.
# axis=None, axis=0, axis=1과 같이 지정한다.

In [76]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


합계: 배열.sum(axis), np.sum(배열, axis)

In [ ]:
# axis=None, 생략시 기본값
# axis=None은 전체 배열을 하나의 배열로 간주하고 집계 함수의 범위를 전체 배열로 정의한다.

<img src="./numpyImage02.jpg" width=200 align="left"/>

In [80]:
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

45
45
45
45


In [82]:
# axis=0은 행을 기준으로 각 행의 동일한 인덱스 요소를 그룹으로 연결한다. => 각 열의 합계

<img src="./numpyImage03.jpg" width=200 align="left"/>

In [81]:
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[12 15 18]
[12 15 18]


In [83]:
# axis=1은 열을 기준으로 각 열의 동일한 인덱스 요소를 그룹으로 연결한다. => 각 행의 합계

<img src="./numpyImage04.jpg" width=200 align="left"/>

In [84]:
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[ 6 15 24]
[ 6 15 24]


최대값: 배열.max(axis), np.max(배열, axis)  
최소값: 배열.min(axis), np.min(배열, axis)

In [85]:
print(a.max())
print(a.max(axis=None))
print(np.min(a))
print(np.min(a, axis=None))

9
9
1
1


In [87]:
print(a.max(axis=0))
print(np.max(a, axis=0))
print(a.min(axis=0))
print(np.min(a, axis=0))

[7 8 9]
[7 8 9]
[1 2 3]
[1 2 3]


In [88]:
print(a.max(axis=1))
print(np.max(a, axis=1))
print(a.min(axis=1))
print(np.min(a, axis=1))

[3 6 9]
[3 6 9]
[1 4 7]
[1 4 7]


누적 합계: 배열.cumsum(axis), np.cumsum(배열, axis)

In [93]:
print(a.cumsum())
print(np.cumsum(a))
print(a.cumsum(axis=None))
print(np.cumsum(a, axis=None))

[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]


In [94]:
print(a.cumsum(axis=0))
print(np.cumsum(a, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [95]:
print(a.cumsum(axis=1))
print(np.cumsum(a, axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


평균: 배열.mean(axis), np.mean(배열, axis)

In [96]:
print(a.mean())
print(np.mean(a))
print(a.mean(axis=None))
print(np.mean(a, axis=None))

5.0
5.0
5.0
5.0


In [97]:
print(a.mean(axis=0))
print(np.mean(a, axis=0))

[4. 5. 6.]
[4. 5. 6.]


In [98]:
print(a.mean(axis=1))
print(np.mean(a, axis=1))

[2. 5. 8.]
[2. 5. 8.]


중위수: np.median(배열, axis)

In [103]:
print(np.median(a))
print(np.median(a, axis=None))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

5.0
5.0
[4. 5. 6.]
[2. 5. 8.]


표준편차: 배열.std(axis), np.std(배열, axis)

In [104]:
print(a.std())
print(np.std(a))
print(a.std(axis=None))
print(np.std(a, axis=None))

2.581988897471611
2.581988897471611
2.581988897471611
2.581988897471611


In [105]:
print(a.std(axis=0))
print(np.std(a, axis=0))

[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]


In [107]:
print(a.std(axis=1))
print(np.std(a, axis=1))

[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]


브로드 캐스팅 => 다대일 연산

In [109]:
# shape이 같은 배열의 이항 연산은 배열 요소별로 실행된다.
# 배열의 shape이 다를 경우 배열의 형상을 맞추는 아래 그림과 같은 브로드 캐스팅 과정을 거쳐서 실행된다.

<img src="./numpyImage05.jpg" width=800 align="left"/>

In [112]:
a = np.arange(1, 25).reshape(4, 6)
print(a)
b = np.arange(25, 49).reshape(4, 6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [113]:
# 두 배열의 shape이 같은 경우
print(a + b)

[[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


shape이 다른 배열의 연산  
shape이 다른 배열 사이의 이항 연산에서 브로드 캐스팅 발생 시 배열을 같은 shape으로 만든 후 연산을 실행한다.

In [115]:
# 배열과 스칼라(단일 값)의 연산
# 배열과 스칼라 사이의 이항 연산 시 스칼라를 배열로 변환한다.
a = np.arange(1, 25).reshape(4, 6)
print(a)
print(a + 100)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [117]:
# a + 100은 다음과 같은 과정을 거쳐 처리된다.
new_arr = np.full_like(a, 100)
print(new_arr)
print(a + new_arr)

[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [121]:
# shape이 다른 배열의 연산
a = np.arange(5).reshape(1, 5)
print(a)
b = np.arange(5).reshape(5, 1)
print(b)
print(a + b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


벡터 연산

In [122]:
# 넘파이는 벡터 연산을 지원한다.
# 넘파이의 집합 연산에서는 벡터화 기능이 있어서 배열 처리에 대해 벡터 연산을 적용할 경우 속도가 100배 이상 빠르다.
# 머신러닝에서 선형대수 연산을 처리할 때 매우 높은 효과(효율)을 낼 수 있다.
a = np.arange(1, 10000001, dtype=np.int64)
print(a)

[       1        2        3 ...  9999998  9999999 10000000]


In [126]:
%%time
result = 0
for i in a:
    result += i
print(result)

50000005000000
Wall time: 2.91 s


In [128]:
%%time
result = np.sum(a)
print(result)

50000005000000
Wall time: 15 ms


배열 복사

In [129]:
# ndarray 배열에 대한 인덱싱, 슬라이싱(subset)의 결과는 새로운 배열이 아닌 원본 배열의 view 이다.
# 반환된 배열의 값을 변경하면 원본 배열에 변경한 내용이 반영된다. => 원본과 사본이 같은 메모리를 사용한다.
# 따라서, 원본 배열로 부터 새로운 배열을 생성하기 위해서 copy() 함수를 사용해야 한다.
# copy() 함수로 복사한 배열은 원본 배열과 완전히 다른 별도의 배열이 된다.

In [130]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [133]:
# 행에 ':'만 사용하면 처음부터 끝까지(어떤 행이라도 상관없이, 행 전체)를 의미한다.
print(a[:, 0]) # 행은 어떤 행이 나와도 상관없고 열은 무조건 0열을 슬라이싱 한다.

[1 4 7]


In [134]:
a[:, 0] = 999
print(a[:, 0])

[999 999 999]


In [135]:
print(a)

[[999   2   3]
 [999   5   6]
 [999   8   9]]


In [136]:
copied_a = np.copy(a)
print(copied_a)

[[999   2   3]
 [999   5   6]
 [999   8   9]]


In [137]:
print(copied_a[:, 0])

[999 999 999]


In [139]:
copied_a[:, 0] = 777
print(copied_a[:, 0])

[777 777 777]


In [142]:
print(copied_a)

[[777   2   3]
 [777   5   6]
 [777   8   9]]


In [144]:
print(a)

[[999   2   3]
 [999   5   6]
 [999   8   9]]


배열 정렬

In [ ]:
# ndarray 객체는 axis를 기준으로 요소를 정렬하는 sort() 함수를 제공한다.

In [147]:
unsorted_arr = np.random.random((3, 3))
print(unsorted_arr)

[[0.95354985 0.21097842 0.36052525]
 [0.54937526 0.27183085 0.46060162]
 [0.69616156 0.5003559  0.71607099]]


In [148]:
# 정렬 작업을 위해 원본을 복사한다.
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

In [149]:
# 배열.sort()
# sort() 함수는 axis으 기본값이 None이 아니고 -1이다.
# -1은 현재 배열의 마지막 axis를 의미하고 unsorted_arr 배열은 2차원 배열이므로 마지막 axis는 1이다.
# 배열.sort()와 배열.sort(axis=-1)와 배열.sort(axis=1)의 결과는 같다.

In [150]:
unsorted_arr1.sort()
print(unsorted_arr1)

[[0.21097842 0.36052525 0.95354985]
 [0.27183085 0.46060162 0.54937526]
 [0.5003559  0.69616156 0.71607099]]


In [151]:
unsorted_arr1.sort(axis=-1)
print(unsorted_arr1)

[[0.21097842 0.36052525 0.95354985]
 [0.27183085 0.46060162 0.54937526]
 [0.5003559  0.69616156 0.71607099]]


In [152]:
unsorted_arr1.sort(axis=1)
print(unsorted_arr1)

[[0.21097842 0.36052525 0.95354985]
 [0.27183085 0.46060162 0.54937526]
 [0.5003559  0.69616156 0.71607099]]


In [153]:
unsorted_arr1.sort(axis=0)
print(unsorted_arr1)

[[0.21097842 0.36052525 0.54937526]
 [0.27183085 0.46060162 0.71607099]
 [0.5003559  0.69616156 0.95354985]]
