In [1]:
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('data\n', arr)

인덱싱

In [2]:
# 배열의 각 요소는 axis 인덱스로 참조할 수 있다.
# 1차원 배열은 1개의 인덱스, 2차원 배열은 2개의 인덱스, 3차원 배열은 3개의 인덱스 요소를 참조할 수 있다.
# 인덱싱 작업시 [행][열]과 같이 인덱스를 지정하거나 [행, 열]과 같이 인덱스를 지정할 수 있다.

In [3]:
# 1차원 배열
a = np.arange(24)
print(a)
# 1차원 배열 요소 참조 및 변경
print(a[5])
a[0] = 10000
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
5
[10000     1     2     3     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23]


In [4]:
# 2차원 배열
a = np.arange(24).reshape(4, 6)
print(a)
# 2차원 배열 요소 참조 및 변경
print(a[0][1])
print(a[0, 1])
a[0][1] = 10000
a[2, 4] = 20000
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1
1
[[    0 10000     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15 20000    17]
 [   18    19    20    21    22    23]]


In [5]:
# 3차원 배열
a = np.arange(24).reshape(2, 4, 3)
print(a)
# 3차원 배열 요소 참조 및 변경
print(a[0][2][1])
print(a[1, 2, 2])
a[0][2][1] = 99999
a[1, 2, 2] = 77777
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
7
20
[[[    0     1     2]
  [    3     4     5]
  [    6 99999     8]
  [    9    10    11]]

 [[   12    13    14]
  [   15    16    17]
  [   18    19 77777]
  [   21    22    23]]]


슬라이싱

In [6]:
# 1차원 슬라이싱
a = np.arange(24)
print(a)
print(a[2:6])
print(a[:6])
print(a[2:])
print(a[:])
print(a[::2])
print(a[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[2 3 4 5]
[0 1 2 3 4 5]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [7]:
# 2차원 배열 슬라이싱
a = np.arange(1, 25).reshape(4, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


<img src="./numpyImage06.jpg" width=800 align="left"/>

In [8]:
# 2차원 배열을 슬라이싱 할 때 열을 슬라이싱하려면 [] 내부에 행과 열을 모두 입력해야 한다.
print(a[1:3]) # 행 단위로 슬라이싱을 하려면 열을 생략하면 된다.
print(a[:, 1:4]) # 열 단위로 슬라이싱을 하려면 행을 생략할 수 없고 ':'을 써야한다.
print(a[1:3, 1:5])

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]
 [20 21 22]]
[[ 8  9 10 11]
 [14 15 16 17]]


In [9]:
print(a[1:3])
# 슬라이싱 작업시 []를 연속해서 사용하면 앞의 슬라이싱 결과를 가지고 뒤의 슬라이싱을 실행한다.
# 아래와 같이 실행하면 a[1:3]가 먼저 실행되고 실행된 결과를 가지고 [1:5]을 행으로 인식해서 슬라이싱 한다.
# [행][열]과 같은 방식으로는 2차원 배열 이상의 인덱싱이 불가능하므로 반드시 [행, 열]과 같은 방식을
# 사용해야 한다.
print(a[1:3][1:5])
print((a[1:3])[1:5])
print(a[:][1:4]) # '[:]'는 배열 전체이고, 배열 전체에서 [1:4]를 행으로 인식해서 슬라이싱한다.

[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[13 14 15 16 17 18]]
[[13 14 15 16 17 18]]
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [10]:
# 음수 인덱싱을 이용한 범위 지정: -1은 마지막 요소의 인덱스이다.
print(a[1:-1, 1:-1])

[[ 8  9 10 11]
 [14 15 16 17]]


<img src="./numpyImage07.jpg" width=800 align="left"/>

In [11]:
# 슬라이싱을 이용한 데이터 수정
print(a)
slide_arr = a[1:3, 1:5]
print(slide_arr)
print(slide_arr[:, 1:3])
# 슬라이싱의 결과는 원본의 view이므로(메모리를 공유한다) 슬라이싱 결과를 수정하면 원본도 같이 수정된다.
slide_arr[:, 1:3] = 99999
print(slide_arr[:, 1:3])
print(slide_arr)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 8  9 10 11]
 [14 15 16 17]]
[[ 9 10]
 [15 16]]
[[99999 99999]
 [99999 99999]]
[[    8 99999 99999    11]
 [   14 99999 99999    17]]
[[    1     2     3     4     5     6]
 [    7     8 99999 99999    11    12]
 [   13    14 99999 99999    17    18]
 [   19    20    21    22    23    24]]


불린 인덱싱 => 전체 데이터에서 특정 조건을 만족하는 데이터를 추출할 경우 많이 사용된다.  
넘파이의 불린 인덱싱은 각 배열 요소의 선택 여부를 True, False로 지정하는 방식으로 True를 선택한다.

In [12]:
a = np.arange(1, 25).reshape(4, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [13]:
# a 배열에서 요소의 값이 짝수인 요소의 총 합계
even_arr = a % 2 # 브로드 캐스팅
print(even_arr)
even_arr = a % 2 == 0 # 불린 인덱싱을 하기위해 연산 결과를 논리값을 만든다.
print(even_arr)

[[1 0 1 0 1 0]
 [1 0 1 0 1 0]
 [1 0 1 0 1 0]
 [1 0 1 0 1 0]]
[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [14]:
print(a[a % 2 == 0])
print(a[even_arr])

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [15]:
print(np.sum(a))
print(np.sum(a[a % 2 == 0]))
print(np.sum(a[a % 2 == 1]))

300
156
144


배열 변환  
배열을 변환하는 방법은 전치, 배열 shape 변환, 배열 요소 추가, 배열 분리 등이 있다.

In [16]:
# 전치는 행렬의 인덱스가 바뀌는 것이다.

<img src="./numpyImage08.jpg" width=200 align="left"/>

In [17]:
# 넘파이에서 배열을 전치하기 위해 배열.T 속성을 사용한다.
a = np.arange(1, 7).reshape(2, 3)
print(a)
print(a.T) # 소문자 't'를 사용하면 에러가 발생된다.

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
# 배열 형태 변경
# 넘파이는 배열의 shape을 변경하는 reshape() 메소드와 ravel() 메소드를 제공한다.
# reshape() 메소드는 데이터 변경없이 지정된 shape으로 배열의 형태를 변환한다.
# ravel() 함수는 배열의 shape을 무조건 1차원 배열로 변환한다.

In [19]:
a = np.arange(1, 13).reshape(1, 12)
print(a)
print(a.reshape(2, 6)) # 배열의 차원을 변경해서 보여주기만 한다.
print(a)
a = a.reshape(2, 6) # 원본이 변경되게 하려면 변경한 결과를 다시 넣어줘야 한다.
print(a)
print(a.ravel()) # 배열의 차원을 변경해서 보여주기만 한다.
print(a)
a = a.ravel() # 원본이 변경되게 하려면 변경한 결과를 다시 넣어줘야 한다.
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
# ravel() 함수도 인덱싱, 슬라이싱의 경우처럼 원본 배열의 view를 보여준다.
# ravel() 함수가 반환한 배열을 수정하면 원본 배열의 내용이 같이 수정된다.
a = np.arange(1, 13).reshape(1, 12)
print(a)
b = a.ravel()
print(b)
b[0] = 99999
print(b)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[99999     2     3     4     5     6     7     8     9    10    11    12]
[[99999     2     3     4     5     6     7     8     9    10    11    12]]


In [21]:
# reshape() 함수도 인덱싱, 슬라이싱의 경우처럼 원본 배열의 view를 보여준다.
# reshape() 함수가 반환한 배열을 수정하면 원본 배열의 내용이 같이 수정된다.
a = np.arange(1, 13).reshape(1, 12)
print(a)
b = a.reshape(3, 2, 2)
print(b)
b[1][0][1] = 99999
print(b)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[    1     2]
  [    3     4]]

 [[    5 99999]
  [    7     8]]

 [[    9    10]
  [   11    12]]]
[[    1     2     3     4     5 99999     7     8     9    10    11    12]]


In [22]:
# resize() 메소드는 배열의 shape과 크기를 변경한다.
# np.resize(배열, new_shape), 배열.resize(new_shape)
# resize()와 reshape() 메소드는 shape을 변경한다는 부분에서는 동일하지만 reshape() 메소드는 요소의 개수가 변경되면
# 에러가 발생되지만 resize() 메소드는 shape을 변경하는 과정에서 요소의 개수를 늘이거나 줄일 수 있다.

In [23]:
a = np.arange(1, 13).reshape(1, 12)
print(a)
print(np.resize(a, (6, 2))) # 원본을 변경하지 않는다.
print(a)
a.resize(6, 2) # 원본을 변경한다.
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [39]:
# a = np.arange(1, 13).reshape(1, 12)
a = np.arange(1, 13)
# a = np.random.randint(1, 10, (1, 12))
print(a)
# a.reshape(2, 10) # reshape() 메소드는 원본 요소의 개수와 변경하려는 요소의 개수가 같아야 한다.

# np.resize(배열, new_shape) 형식은 실행결과 원붠 데이터가 변경되지 않기 때문에 다른 변수에 저장해 사용한다.
# 배열 요소의 개수가 12개에서 20개로 늘어나고 늘어난 요소에는 원본 내용이 반복되서 채워진다.
b = np.resize(a, (2, 10))
print(b)
# 배열 요소의 개수가 12개에서 10개로 줄어들고 남는 데이터는 사라진다.
c = np.resize(a, (1, 10))
print(c)

# 배열.resize(new_shape) 형식은 실행하면 원본 데이터가 변경되므로 원본 그대로 사용하면 된다.
# 배열 요소의 개수가 12개에서 20개로 늘어나고 늘어난 요소에는 0이 반복되서 채워진다.
# 배열 요소의 개수가 12개에서 10개로 줄어들면 남는 데이터는 사라진다.
# reshape이 적용된 배열에는 사용할 수 없다.
a.resize(2, 10)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12  1  2  3  4  5  6  7  8]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12  0  0  0  0  0  0  0  0]]


In [40]:
# append() 메소드는 배열 끝에 데이터(배열)을 추가한다.
# axis로 데이터가 추가되는 방향을 지정할 수 있다.
# np.append(배열, 추가할 데이터, axis)

In [43]:
a = np.arange(1, 10).reshape(3, 3)
print(a)
b = np.arange(10, 19).reshape(3, 3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [45]:
# axis를 지정하지 않으면 None으로 지정되며 1차원 배열로 변환되서 결합된다.
# result = np.append(a, b, axis=None)
result = np.append(a, b)
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [53]:
# axis를 0으로 지정하면 배열의 아래쪽에 배열이 추가(열방항으로)되기 때문에 행의 개수는 달라도 상관없지만
# 열의 개수는 반드시 같아야 한다.
result = np.append(a, b, axis=0)
print(result)
print('=' * 40)

c = np.arange(19, 31).reshape(4, 3)
print(c)
result = np.append(a, c, axis=0) # 행의 개수는 달라도 상관없다.
print(result)
print('=' * 40)

c = np.arange(19, 31).reshape(3, 4)
print(c)
result = np.append(a, c, axis=0) # 열의 개수가 달라서 에러가 발생된다.
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
[[19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [56]:
# axis를 1으로 지정하면 배열의 오른쪽에 배열이 추가(행방항으로)되기 때문에 열의 개수는 달라도 상관없지만
# 행의 개수는 반드시 같아야 한다.
result = np.append(a, b, axis=1)
print(result)
print('=' * 40)

c = np.arange(19, 31).reshape(3, 4)
print(c)
result = np.append(a, c, axis=1) # 열행의 개수는 달라도 상관없다.
print(result)
print('=' * 40)

c = np.arange(19, 31).reshape(4, 3)
print(c)
result = np.append(a, c, axis=1) # 행의 개수가 달라서 에러가 발생된다.
print(result)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
[[ 1  2  3 19 20 21 22]
 [ 4  5  6 23 24 25 26]
 [ 7  8  9 27 28 29 30]]
[[19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [57]:
# insert() 메소드는 지정된 index 위치에 데이터를 삽입한다.
# axis로 데이터가 삽입되는 방향을 지정할 수 있다.
# insert(배열, index, 데이터, axis)
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
# axis를 지정하지 않으면 1차원 배열로 변환하고 index 위치에 데이터를 삽입한다.
# print(np.insert(a, 1, 77777))
print(np.insert(a, 1, 77777, axis=None))

[    1 77777     2     3     4     5     6     7     8     9]


In [60]:
# axis을 0으로 지정하면 열 방향 index 전체에 데이터를 삽입한다.
print(np.insert(a, 1, 77777, axis=0))

[[    1     2     3]
 [77777 77777 77777]
 [    4     5     6]
 [    7     8     9]]


In [62]:
# axis을 1으로 지정하면 행 방향 index 전체에 데이터를 삽입한다.
print(np.insert(a, 1, 77777, axis=1))

[[    1 77777     2     3]
 [    4 77777     5     6]
 [    7 77777     8     9]]


In [63]:
# delete() 메소드는 지정된 index의 데이터를 삭제한다.
# axis로 데이터가 삭제되는 방향을 지정할 수 있다.
# np.delete(배열, index, axis)
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
# axis를 지정하지 않으면 1차원 배열로 변환하고 index 위치에 데이터를 삭제한다. 
# print(np.delete(a, 1))
print(np.delete(a, 1, axis=None))

[1 3 4 5 6 7 8 9]


In [68]:
# axis을 0으로 지정하면 열 방향 index 전체 데이터를 삭제한다.
print(np.delete(a, 1, axis=0))

[[1 2 3]
 [7 8 9]]


In [70]:
# axis을 1으로 지정하면 행 방향 index 전체 데이터를 삭제한다.
print(np.delete(a, 1, axis=1))

[[1 3]
 [4 6]
 [7 9]]


배열 분리  
넘파이는 수평 방향으로 분할하는 hsplit() 메소드와 수직 방향으로 분할하는 vsplit() 메소드를 제공한다.

In [71]:
# np.hsplit(배열, 분할할 배열의 개수), np.hsplit(배열, [분할할 인덱스])
a = np.arange(1, 25).reshape(4, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [77]:
result = np.hsplit(a, 2) # hsplit() 메소드의 실행 결과는 파이썬 리스트이다.
print(type(result))
print(result)
print(type(result[0]))
print(type(result[1]))
print(result[0])
print(result[1])

<class 'list'>
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]


<img src="./numpyImage09.jpg" width=800 align="left"/>

In [78]:
result = np.hsplit(a, 3)
print(result)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


<img src="./numpyImage10.jpg" width=800 align="left"/>

In [79]:
result = np.hsplit(a, [1, 3, 5])
print(result)

[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]]), array([[ 6],
       [12],
       [18],
       [24]])]


<img src="./numpyImage11.jpg" width=800 align="left"/>

In [80]:
# np.vsplit(배열, 분할할 배열의 개수), np.hsplit(배열, [분할할 인덱스])
a = np.arange(1, 25).reshape(4, 6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [81]:
result = np.vsplit(a, 2)
print(result)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


<img src="./numpyImage12.jpg" width=800 align="left"/>

In [85]:
result = np.vsplit(a, 4)
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


<img src="./numpyImage13.jpg" width=800 align="left"/>

In [86]:
result = np.vsplit(a, [1, 3])
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


<img src="./numpyImage14.jpg" width=800 align="left"/>