# 2차원 리스트

<img src="./2Dim.png" width="1000" align="left"/>

In [3]:
# 리스트이름 = [[0] * 열개수 for i in range(행개수)]
data = [[0] * 5 for i in range(4)]
print(data)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


# 외부 라이브러리를 커맨드(까만) 창이 아니라 jupyter notebook에서 설치하기
!pip install 라이브러리이름 => '!'를 붙여서 pip install을 실행하면 된다.

In [6]:
# !pip install numpy
import numpy as np

In [10]:
npArray = np.array(data)
print(npArray)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
print(len(data)) # 행의 개수
print(len(data[0])) # 열의 개수

4
5


In [13]:
for i in range(len(data)):
    print(data[i])

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [15]:
for i in range(len(data)):
    for j in range(len(data[0])):
        print(data[i][j], end=' ')
    print()

0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 
0 0 0 0 0 


<img src="./2Dim_Zigzag.png" width="300" align="left"/>

In [24]:
row, col = map(int, input('2차원 리스트를 만들려하는 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0 # 리스트에 1씩 증가하며 채워질 숫자가 기억되는 변수

for i in range(len(data)): # 행
    # 짝수행은 숫자가 왼쪽에서 오른쪽으로 채워지고 홀수행은 숫자가 오른쪽에서 왼쪽으로 채워진다.
    # 짝수행인가 홀수행인가 판단한다.
    if i % 2 == 0: # 짝수인가?
        # 짝수행은 왼쪽에서 오른쪽으로 숫자를 채운다. j => 0, 1, 2, 3, 4
        for j in range(col):
            n += 1
            data[i][j] = n
    else:
        # 홀수행은 오른쪽에서 왼쪽으로 숫자를 채운다. j => 4, 3, 2, 1, 0
        for j in range(col - 1, -1, -1):
            n += 1
            data[i][j] = n
            
for i in range(len(data)):
    for j in range(len(data[0])):
        print('{:3d} '.format(data[i][j]), end='')
    print()

2차원 리스트를 만들려하는 행과 열의 개수: 7 15
  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15 
 30  29  28  27  26  25  24  23  22  21  20  19  18  17  16 
 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45 
 60  59  58  57  56  55  54  53  52  51  50  49  48  47  46 
 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75 
 90  89  88  87  86  85  84  83  82  81  80  79  78  77  76 
 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 


In [29]:
row, col = map(int, input('2차원 리스트를 만들려하는 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]

n = 0
start = 0 # 2차원 리스트에 숫자가 채워지기 시작하는 열의 인덱스
end = col - 1 # 2차원 리스트에 숫자가 채워지는 마지막 열의 인덱스
sw = 1 # start 부터 end 까지 증가치로 사용할 변수

for i in range(row):
    # i = 0, sw = 1, j = range(0, 5, 1) => 0, 1, 2, 3, 4
    # i = 1, sw = -1, j = range(4, -1, -1) => 4, 3, 2, 1, 0
    # i = 2, sw = 1, j = range(0, 5, 1) => 0, 1, 2, 3, 4
    # i = 3, sw = -1, j = range(4, -1, -1) => 4, 3, 2, 1, 0
    for j in range(start, end + sw, sw):
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
    sw *= -1
# ===== for i

for i in range(len(data)):
    for j in range(len(data[0])):
        print('{:3d} '.format(data[i][j]), end='')
    print()

2차원 리스트를 만들려하는 행과 열의 개수: 7 9
  1   2   3   4   5   6   7   8   9 
 18  17  16  15  14  13  12  11  10 
 19  20  21  22  23  24  25  26  27 
 36  35  34  33  32  31  30  29  28 
 37  38  39  40  41  42  43  44  45 
 54  53  52  51  50  49  48  47  46 
 55  56  57  58  59  60  61  62  63 


In [30]:
row, col = map(int, input('2차원 리스트를 만들려하는 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]

n = 0
start = [i for i in range(col)] # 0, 1, 2, 3, 4
end = [i for i in range(col - 1, -1, -1)] # 4, 3, 2, 1, 0

for i in range(row):
    for j in start:
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
# ===== for i

for i in range(len(data)):
    for j in range(len(data[0])):
        print('{:3d} '.format(data[i][j]), end='')
    print()

2차원 리스트를 만들려하는 행과 열의 개수: 4 5
  1   2   3   4   5 
 10   9   8   7   6 
 11  12  13  14  15 
 20  19  18  17  16 
